{{- if .Values.component.metanode }}
{{- $envAll := . }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metanode
  labels:
{{ tuple $envAll .Release.Namespace "metanode" | include "helm-toolkit.metadata_labels" | indent 4 }}
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
{{ tuple $envAll .Release.Namespace "metanode" | include "helm-toolkit.labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple $envAll .Release.Namespace "metanode" | include "helm-toolkit.labels" | indent 8 }}
    spec:
      terminationGracePeriodSeconds: 60
      {{- with .Values.metanode.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.metanode.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      hostNetwork: true
      priorityClassName: cubefs-high-priority
      hostPID: false
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: check-master-service
          image: {{ .Values.image.server }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "/cfs/bin/check-master-service.sh"]
          env:
            - name: CBFS_MASTER_SERVICE_PORT
              value: {{ include "cubefs.master-service.with.port" . | quote }}
          volumeMounts:
            - name: cubefs-bin
              mountPath: /cfs/bin/check-master-service.sh
              subPath: check-master-service.sh
              readOnly: true
      containers:
        - name: metanode-pod
          image: {{ .Values.image.server }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "/cfs/bin/start.sh"]
          securityContext:
            privileged: true
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: CBFS_METANODE_LOCALIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
{{ tuple $envAll "port" .Values.metanode.port | include "helm-toolkit.utils.container_port" | indent 12 }}
{{ tuple $envAll "prof" .Values.metanode.prof | include "helm-toolkit.utils.container_port" | indent 12 }}
{{ tuple $envAll "raft-heartbeat" .Values.metanode.raft_heartbeat | include "helm-toolkit.utils.container_port" | indent 12 }}
{{ tuple $envAll "raft-replica" .Values.metanode.raft_replica | include "helm-toolkit.utils.container_port" | indent 12 }}
{{ tuple $envAll "exporter-port" .Values.metanode.exporter_port | include "helm-toolkit.utils.container_port" | indent 12 }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.metanode.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: {{ .Values.metanode.port }}
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          volumeMounts:
            - name: cubefs-bin
              mountPath: /cfs/bin/start.sh
              subPath: start-metanode.sh
              readOnly: true
            - name: cubefs-conf
              mountPath: /conf/metanode.json
              subPath: metanode.json
            {{- if .Values.path.log }}
            - name: pod-log-path
              mountPath: /cfs/logs
              readOnly: false
            {{- end }}
            {{- if .Values.path.data }}
            - name: pod-data-path
              mountPath: /cfs/data
              readOnly: false
            {{- end }}
{{ tuple $envAll .Values.metanode.resources | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
        - name: cubefs-bin
          configMap:
            name: cubefs-bin
            defaultMode: 0555
        - name: cubefs-conf
          configMap:
            name: cubefs-conf
            defaultMode: 0555
        {{- if .Values.path.log }}
        - name: pod-log-path
          hostPath:
            path: {{ .Values.path.log }}
        {{- end }}
        {{- if .Values.path.data }}
        - name: pod-data-path
          hostPath:
            path: {{ .Values.path.data }}
        {{- end }}
{{ end }}






