{{- if .Values.component.objectnode }}
{{- $envAll := . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectnode
  labels:
{{ tuple $envAll .Release.Namespace "objectnode" | include "helm-toolkit.metadata_labels" | indent 4 }}
spec:
  replicas: {{ .Values.objectnode.replicas }}
  selector:
    matchLabels:
{{ tuple $envAll .Release.Namespace "objectnode" | include "helm-toolkit.labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple $envAll .Release.Namespace "objectnode" | include "helm-toolkit.labels" | indent 8 }}
    spec:
      terminationGracePeriodSeconds: 60
      {{- with .Values.objectnode.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.objectnode.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      initContainers:
        - name: check-master-service
          image: {{ .Values.image.server }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "/cfs/bin/check-master-service.sh"]
          env:
            - name: CBFS_MASTER_SERVICE_PORT
              value: {{ include "cubefs.master-service.with.port" . | quote }}
          volumeMounts:
            - name: cubefs-bin
              mountPath: /cfs/bin/check-master-service.sh
              subPath: check-master-service.sh
              readOnly: true
      containers:
        - name: objectnode-pod
          image: {{ .Values.image.server }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "/cfs/bin/start.sh"]
          securityContext:
            privileged: true
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
{{ tuple $envAll "port" .Values.objectnode.port | include "helm-toolkit.utils.container_port" | indent 12 }}
{{ tuple $envAll "prof" .Values.objectnode.prof | include "helm-toolkit.utils.container_port" | indent 12 }}
{{ tuple $envAll "exporter-port" .Values.objectnode.exporter_port | include "helm-toolkit.utils.container_port" | indent 12 }}
          volumeMounts:
            - name: cubefs-bin
              mountPath: /cfs/bin/start.sh
              subPath: start-objectnode.sh
              readOnly: true
            - name: cubefs-conf
              mountPath: /cfs/conf/objectnode.json
              subPath: objectnode.json
{{ tuple $envAll .Values.objectnode.resources | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
        - name: cubefs-bin
          configMap:
            name: cubefs-bin
            defaultMode: 0555
        - name: cubefs-conf
          configMap:
            name: cubefs-conf
            defaultMode: 0555
{{ end }}





