{{- if .Values.component.monitor }}
{{- $envAll := . }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  labels:
{{ tuple $envAll .Release.Namespace "consul" | include "helm-toolkit.metadata_labels" | indent 4 }}
  
spec:
  replicas: {{ .Values.consul.replicas }}
  selector:
    matchLabels:
{{ tuple $envAll .Release.Namespace "consul" | include "helm-toolkit.labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple $envAll .Release.Namespace "consul" | include "helm-toolkit.labels" | indent 8 }}
    spec:
      containers:
        - name: consul-pod
          image: {{ $.Values.image.consul }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: CONSUL_LOCAL_CONFIG
              value: "{\"ports\": {\"http\": {{.Values.consul.port}} }}" 
          ports:
{{ tuple $envAll "port" .Values.consul.port | include "helm-toolkit.utils.container_port" | indent 12 }}
{{ tuple $envAll $envAll.Values.consul.resources | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ end }}

