{{- if .Values.component.master }}
{{- $envAll := . }}

---
apiVersion: v1
kind: Service
metadata:
  name: master-service
  
spec:
  ports:
    - port: {{ .Values.master.port }}
      protocol: TCP
      targetPort: {{ .Values.master.port }}
  selector:
{{ tuple $envAll .Release.Namespace "master" | include "helm-toolkit.labels" | indent 4 }}
{{ end }}