{{- if .Values.component.monitor }}
{{- $envAll := . }}

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  
spec:
  ports:
    - port: {{ .Values.prometheus.port }}
      protocol: TCP
      targetPort: {{ .Values.prometheus.port }}
  selector:
{{ tuple $envAll .Release.Namespace "prometheus" | include "helm-toolkit.labels" | indent 4 }}
{{ end }}