{{- if .Values.component.master }}
{{- $envAll := . }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: master
  labels:
{{ tuple $envAll .Release.Namespace "master" | include "helm-toolkit.metadata_labels" | indent 4 }}
spec:
  updateStrategy:
    type: OnDelete
  replicas: {{ .Values.master.replicas }}
  serviceName: master-service
  selector:
    matchLabels:
{{ tuple $envAll .Release.Namespace "master" | include "helm-toolkit.labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple $envAll .Release.Namespace "master" | include "helm-toolkit.labels" | indent 8 }}
    spec:
      terminationGracePeriodSeconds: 60
      {{- with .Values.master.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.master.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      # Master can not deploy in a same node, port will conflict.
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/application
                    operator: In
                    values:
                      - {{ .Release.Namespace }}
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - "master"
              topologyKey: kubernetes.io/hostname
      hostNetwork: true
      priorityClassName: cubefs-high-priority
      hostPID: false
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: master-pod
          image: {{ .Values.image.server }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "/cfs/bin/start.sh"]
          securityContext:
            privileged: true
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
{{ tuple $envAll "port" .Values.master.port | include "helm-toolkit.utils.container_port" | indent 12 }}
{{ tuple $envAll "prof" .Values.master.prof | include "helm-toolkit.utils.container_port" | indent 12 }}
{{ tuple $envAll "exporter-port" .Values.master.exporter_port | include "helm-toolkit.utils.container_port" | indent 12 }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.master.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: {{ .Values.master.port }}
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          volumeMounts:
            - name: cubefs-bin
              mountPath: /cfs/bin/start.sh
              subPath: start-master.sh
              readOnly: true
            - name: cubefs-conf
              mountPath: /conf/master.json
              subPath: master.json
            {{- if .Values.path.log }}
            - name: pod-log-path
              mountPath: /cfs/logs
              readOnly: false
            {{- end }}
            {{- if .Values.path.data }}
            - name: pod-data-path
              mountPath: /cfs/data
              readOnly: false
            {{- end }}
{{ tuple $envAll .Values.master.resources | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
        - name: cubefs-bin
          configMap:
            name: cubefs-bin
            defaultMode: 0555
        - name: cubefs-conf
          configMap:
            name: cubefs-conf
            defaultMode: 0555
        {{- if .Values.path.log }}
        - name: pod-log-path
          hostPath:
            path: {{ .Values.path.log }}
        {{- end }}
        {{- if .Values.path.data }}
        - name: pod-data-path
          hostPath:
            path: {{ .Values.path.data }}
        {{- end }}
{{ end }}







